#!/usr/bin/env bash
#################################
##  Grab astronomy data for computer usage!

HEADER="### This file is autogenerated by $0 do NOT edit manually, pretty please"
ASTRONOMYDATA=/opt/astronomy/data
ETCFILE=/etc/sysconfig/astronomy
TMPFILE=/tmp/astronomy.tmp
## Get your latitude & longitude from http://maps.google.com/
LATITUDE=32.6915332
LONGITUDE=-117.0829808
CONFIG_DATE_FORMAT='%H:%M'

TODAYFILE=${ASTRONOMYDATA}/$(date +%Y%m%d)-data

# astrolink
astrolink()
{
  /usr/bin/ln -sfn ${TODAYFILE} ${ETCFILE}
}

# :(
astronomy_error()
{
  echo 'astronomy_inactive=yes' > "${TODAYFILE}"
  astrolink
  exit 1
}

[ -f "${TODAYFILE}" ] && exit 0 ## Well I don't want this to be called more than once a day

## Make dir for our data
[ ! -d $ASTRONOMYDATA ] && mkdir -p $ASTRONOMYDATA

## This will just grab the unformatted data and place it on your /etc for easy consultation
wget -qO - "https://api.sunrise-sunset.org/json?lat=$LATITUDE&lng=$LONGITUDE&formatted=0&date=today" | /bin/grep '"status":"OK"' | sed -E "s|^\{[\"']+results[\"']+:\{(.*)\},\"status\":\"OK\"}|\1|g" | sed 's|,|\n|g' | sed 's|\"||g' | sed 's|:|=|' > "${TMPFILE}"
#cat /etc/astronomy.json  | /bin/grep '"status":"OK"' | sed -E "s|^\{[\"']+results[\"']+:\{(.*)\},\"status\":\"OK\"}|\1|g" | sed 's|,|\n|g' | sed 's|\"||g' | sed 's|:|=|' > "${TMPFILE}"

# There's no power without Control
[ ! -e "${TMPFILE}" ] && astronomy_error

## There's solace in power
declare -a vars=( $(/bin/cat "${TMPFILE}" | cut -d'=' -f 1) )
echo -e "$HEADER\ndate_check=$(date +%Y-%m-%d)" > "${TODAYFILE}"
(
  . "${TMPFILE}"

  for v in ${vars[@]}; do
    ( ! [[ ${!v} =~ [^0-9]+ ]] ) && echo "${v}=${!v}">>${TODAYFILE} && continue
    echo "${v}=$(date --date "${!v}" +"$CONFIG_DATE_FORMAT")">>"${TODAYFILE}"
  done
) # as-if

## Like good boys, we clean up after ourselves
[ -e "${TMPFILE}" ] && /bin/rm -f "${TMPFILE}"

[ ! -e "${TODAYFILE}" ] && astronomy_error

astrolink
# We are happy
exit 0

### FIN

######### [CREDITS]
## Sunrise Sunset : https://sunrise-sunset.org/api ## Thanks for your API!
